In [11]:
import numpy as np
from keras.layers import Conv2D


In [4]:
labels = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
labels

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [5]:
categories = np.array(["shoe", "shirt", "dress", "bag"])
n_categories = len(categories)
# n_categories
ohe_labels = np.zeros((len(labels), n_categories))
ohe_labels

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
categories[0]

'shoe'

In [7]:
labels[0]

array([1, 0, 0, 0])

In [8]:
labels[0]

array([1, 0, 0, 0])

In [9]:
categories[0]

'shoe'

In [10]:
np.where(categories == labels)

C:\Users\olofs\AppData\Local\Temp\ipykernel_22180\1347875326.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  np.where(categories == labels)


(array([], dtype=int64),)

In [ ]:
for ii in range(len(labels)):
    jj = np.where(categories == labels[ii])
    ohe_labels[ii, jj] = 1
    print(jj)
    # print(ii)


In [ ]:
ohe_labels

In [ ]:
Conv2D()